# Generated by Django 5.1.7 on 2025-04-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('food', 'Харчування'), ('transport', 'Транспорт'), ('entertainment', 'Розваги'), ('other', 'Інше')], max_length=50)),
                ('date', models.DateField()),
                ('time_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
