# Generated by Django 5.1.7 on 2025-04-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='budget',
            name='expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='income',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
