# Generated by Django 5.1.7 on 2025-04-25 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_budget_date_budget_income_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('not_selected', 'Не вибрано'), ('male', 'Чоловік'), ('female', 'Жінка')], default='not_selected', max_length=20)),
                ('language', models.CharField(choices=[('uk', 'Українська'), ('en', 'English')], default='uk', max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
