# Generated by Django 5.1.7 on 2025-04-25 19:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_profile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_registered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
