# Generated by Django 5.1.7 on 2025-04-25 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_profile_email_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
