# Generated by Django 5.1.7 on 2025-04-25 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_profile_email_remove_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='full_name',
            new_name='first_name',
        ),
    ]
