# Generated by Django 5.1.7 on 2025-04-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_profile_first_name_profile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_cache',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='username_cache',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
